name: zebra_rfid_reader_sdk
description: Zebra RFID Reader SDK plugin for Flutter.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.borda.zebra_rfid_reader_sdk
        pluginClass: ZebraRfidReaderSdkPlugin
      ios:
        pluginClass: ZebraRfidReaderSdkPlugin
